### PR TITLE
`bookworm` compatibility

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- `Bookworm` install fails

## Solution

- ????

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by orhtej2** [comment]
!bookwormtestme !testme

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by alexAubin** [comment]
!testme

**Comment by Salamandar** [comment]
Github and its awful way to handle remote PRs… So moved to https://github.com/YunoHost-Apps/mygpo_ynh/pull/32

**Pull request closed without merging**
