### PR TITLE
Update to 2021-10-20

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by Jules-Bertholet** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Review by yalh76 — APPROVED** [review]

**Comment by yalh76** [comment]
@Jules-Bertholet, seems ready ;)

**Pull request merged**
